apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: ghostapp
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-08-01T02:51:22Z"
  generation: 1
  labels:
    app.kubernetes.io/component: ghost
    app.kubernetes.io/instance: ghostapp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-19.3.31
  name: ghostapp
  namespace: default
  resourceVersion: "6597"
  uid: 564af876-def3-4012-905c-03b532ea17ae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ghostapp
      app.kubernetes.io/name: ghost
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/secrets: d107ac58e66bd5d3ca66ddb7c0951c57838d6039e460bf3f71fe0324bfe5073a
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ghost
        app.kubernetes.io/instance: ghostapp
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ghost
        helm.sh/chart: ghost-19.3.31
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: ghostapp
                  app.kubernetes.io/name: ghost
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: GHOST_DATABASE_HOST
          value: ghostapp-mysql
        - name: GHOST_DATABASE_PORT_NUMBER
          value: "3306"
        - name: GHOST_DATABASE_NAME
          value: bitnami_ghost
        - name: GHOST_DATABASE_USER
          value: bn_ghost
        - name: GHOST_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: ghostapp-mysql
        - name: GHOST_HOST
          value: a2598c666af254e2780cd726b4a51f57-704288651.ca-central-1.elb.amazonaws.com/
        - name: GHOST_PORT_NUMBER
          value: "2368"
        - name: GHOST_USERNAME
          value: user
        - name: GHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ghost-password
              name: ghostapp
        - name: GHOST_EMAIL
          value: user@example.com
        - name: GHOST_BLOG_TITLE
          value: User's Blog
        - name: GHOST_ENABLE_HTTPS
          value: "no"
        - name: GHOST_EXTERNAL_HTTP_PORT_NUMBER
          value: "80"
        - name: GHOST_EXTERNAL_HTTPS_PORT_NUMBER
          value: "443"
        - name: GHOST_SKIP_BOOTSTRAP
          value: "no"
        image: docker.io/bitnami/ghost:5.57.0-debian-11-r0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ghostapp
        ports:
        - containerPort: 2368
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/ghost
          name: ghost-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: ghostapp
      serviceAccountName: ghostapp
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghostapp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-08-01T02:52:41Z"
    lastUpdateTime: "2023-08-01T02:52:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-08-01T02:51:22Z"
    lastUpdateTime: "2023-08-01T02:52:41Z"
    message: ReplicaSet "ghostapp-c67c98695" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
